apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "development"
  GATEWAY_HTTP_ADDR: ":8081"
  OTLP_ENDPOINT: "http://jaeger:4318/v1/traces"
  STRIPE_SUCCESS_URL: "http://localhost:3000?payment=success"
  STRIPE_CANCEL_URL: "http://localhost:3000?payment=cancel"
